#----------------------------------------------------------------------
# about.R
# Read me page for app
# JR New, 2015
#----------------------------------------------------------------------
function() {
  box(width = 12, title = "Overview", status = "info", solidHeader = TRUE,
      strong("About"),
      p("sfhip-app is a working prototype of an interactive data visualization web tool created for the ",
        a("San Francisco Health Improvement Partnership (SFHIP)", 
          href = "http://www.sfhip.org/", target = "_blank"),
        " that allows users to explore data on alcohol licenses and crime in the city of San Francisco. ",
        "The tool is available live at ",
        a("http://bit.ly/sf-hip-viz-tool.", 
          href = "https://jrnew.shinyapps.io/sfhip-app", target = "_blank"),
        " This was built in a day for the ",
        a("DataKind San Francisco", 
          href = "http://www.datakind.org/howitworks/datachapters/datakind-sf/", target = "_blank"),
        " DataDive that took place on Mar 27 to 29, 2015."),
      strong("Data"),
      p("Data sets used for sfhip-app are is available from SFHIP, the US Census Bureau ",
        a("American Community Survey", 
          href = "http://www.census.gov/acs/www/", target = "_blank"),
        " and the San Francisco Police Department. Crime rate data aggregated to the census tract ",
        "(based on the 2010 US Census) level was provided by Kris Sankaran, while ",
        a("Bill Chambers", 
          href = "http://billchambers.me/", target = "_blank"), " did the ",
        a("k-means clustering analysis", 
          href = "http://nbviewer.ipython.org/github/anabranch/datadive_201503_sf-health-improvement-partnership/blob/master/clustering/KMeans%20Clustering%20Crime%20%26%20Alcohol%20Off-Site%20Sales%20Locations.ipynb", 
          target = "_blank"),
        "to identify geographical cluster centroids of ",
        "establishments with alcohol licenses and crime incidents."),
      strong("Disclaimer"),
      p("This tool is only a first step towards the final goal of a full-fledged interactive ",
        "data visualization with real-time (or as real-time as possible) updates of various data sources. ",
        "We would advise against drawing any conclusions from the tool at this point as it is still ",
        "pending more rigorous data cleaning and analysis as well as bug fixes."),
      strong("Source code"),
      p("The source code for this tool is available in a GitHub ",
        a("repo.", 
          href = "https://github.com/DataKind-SF/datadive_201503_sf-health-improvement-partnership/tree/master/sfhip-app", 
          target = "_blank")),
      strong("Contact"),
      p("This tool was created by ",
        a("Jin Rou (JR) New.", 
          href = "http://twitter.com/jrnewww", target = "_blank"),
        "For any questions, feedback or suggestions, ",
        "please contact her at newjinrou[at]gmail.com."),
      br(), 
      p("Last updated: 29 Mar 2015",
        br("Created in ",
           a("R", 
             href = "http://www.r-project.org/", target = "_blank"),
           "| Powered by ",
           a("Shiny", 
             href = "http://www.rstudio.com/shiny/", target = "_blank")),
        align = "center")
  )
}
